version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/web/Dockerfile
    image: geo_sensor_gap_web
    command: /start.sh.sh
    volumes:
      - .:/app
    ports:
        - 8000:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting

volumes:
  postgres_data: